credentials:
  usernames:
    tester:
      email: tester@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: tester
      password: tester # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - ea.garciad1@uniandes.edu.co
  - erik172dev@gmail.com